site_name: Programmer en python

plugins: []

theme: readthedocs

extra_css:
    - css/extra.css
    
markdown_extensions:
- admonition
- pymdownx.details #for the pull down markdown
- pymdownx.arithmatex:
    generic: true
- footnotes

nav:
    - Introduction: index.md
    - 'Découverte':
      - 'Introduction': intro/1_intro.md
      - 'Instructions': intro/2_instructions.md
      - 'Variables': intro/3_variables.md
      - 'Boucles': intro/4_boucles.md
      - 'Fonctions': intro/5_fonctions.md
      - 'Conditions': intro/6_conditions.md
      - 'Listes': intro/7_listes.md
      - 'Conclusion': intro/8_conclusion.md
    - 'Les algorithmes de tri':
      - 'Introduction': tri/1_intro.md
      - 'Break & Continue': tri/2_break.md
      - 'Variables': tri/3_variables.md
      - 'Modules': tri/4_modules.md
      - 'Librairies': tri/5_librairies.md


theme: readthedocs
#theme: 'material'
