site_name: Programmation Scratch

plugins: []

theme: readthedocs

extra_css:
    - css/extra.css
    
markdown_extensions:
- admonition
- pymdownx.details #for the pull down markdown
- pymdownx.arithmatex:
    generic: true
- footnotes

nav:
    - Introduction: index.md
    - 'Casse Briques':
      - 'Introduction': intro/introScratch.md
      - 'Interface': intro/interface.md
      - 'Raquette': intro/raquette.md
      - 'Balle': intro/balle.md
      - 'Briques': intro/briques.md
      - 'Conclusion': intro/conclusion.md
    - 'Simulateur':
      - 'Introduction': simu/1_intro.md  
      - 'Structure': simu/2_structure.md  
      - 'Individu': simu/3_individu.md  
      - 'Foule': simu/4_foule.md  
      - 'Infection': simu/5_infection.md  
      - 'Confinement': simu/6_confinement.md  
      - 'Qantificationn': simu/7_quantification.md  
      - 'Conclusion': simu/8_conclusion.md  

theme: readthedocs
#theme: 'material'
